#!/usr/bin/env python3
"""
assemble_final.py — Merge translated chunks (parts/trans_NN.txt) back into a
single bilingual .ass file with `English || Chinese` on every Dialogue line,
keeping the ORIGINAL timestamps from the source subtitle.

Also runs integrity checks and fails loudly if anything is broken:
  - every chunk exists and line count matches the part file
  - idx sequence is contiguous, no duplicates/missing
  - every Dialogue line contains the ` || ` delimiter exactly once
  - no tab characters inside text fields
  - start < end for every line; timeline non-decreasing

Usage:
    python3 assemble_final.py [--out <name.ass>] [--workdir .]

By default the output file shares the MP4's base name (read from the top-level
manifest.json), e.g. "Talk.mp4" -> "Talk.ass". Pass --out to override.

Exit codes: 0 ok, 1 fatal (validation failed — do NOT deliver the file).
"""

import argparse
import json
import os
import re
import sys


def log(msg: str) -> None:
    print(f"[assemble] {msg}", flush=True)


DELIM = " || "


def parse_trans_line(line: str) -> list[str]:
    """Split a translation line on tabs; text fields may contain spaces only."""
    return line.rstrip("\n").split("\t")


def to_seconds(ts: str) -> float:
    """H:MM:SS.cc or HH:MM:SS.cc -> seconds (centiseconds precision)."""
    parts = ts.strip().split(":")
    if len(parts) != 3:
        return -1.0
    try:
        h, m, s = parts
        return int(h) * 3600 + int(m) * 60 + float(s)
    except ValueError:
        return -1.0


def build_standard_header(original_header: list[str] | None = None) -> str:
    """Standard ASS header with a sensible bilingual style."""
    hdr = [
        "[Script Info]",
        "; Generated by nows-ytb-bilingualex",
        "ScriptType: v4.00+",
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour,"
        " OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut,"
        " ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow,"
        " Alignment, MarginL, MarginR, MarginV, Encoding",
        "Style: Default,Noto Sans CJK SC,52,&H00FFFFFF,&H000000FF,"
        "&H00000000,&H96000000,0,0,0,0,100,100,0,0,1,3,1,2,40,40,50,1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV,"
        " Effect, Text",
        "",
    ]
    return "\n".join(hdr)


def resolve_out_name(args) -> str:
    """Default output name = the video's MP4 basename + '.ass' (same name as the
    MP4 file, different extension), read from the top-level manifest.json that
    download.py wrote. Falls back to '01 - bilingual.ass' if unavailable."""
    if args.out:
        return args.out
    top_manifest = os.path.join(args.workdir, "manifest.json")
    if os.path.exists(top_manifest):
        try:
            with open(top_manifest, "r", encoding="utf-8") as f:
                data = json.load(f)
            title = data.get("safe_title")
            if title:
                return f"{title}.ass"
        except Exception as e:
            log(f"WARN: could not read top-level manifest for naming ({e}); "
                "using default name")
    return "01 - bilingual.ass"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=None,
                    help="output filename (default: same base name as the MP4, "
                         "e.g. 'X.mp4' -> 'X.ass')")
    ap.add_argument("--workdir", default=".", help="working directory")
    args = ap.parse_args()

    parts_dir = os.path.join(args.workdir, "parts")
    manifest_path = os.path.join(parts_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        log(f"Manifest not found: {manifest_path}. Run split_translation.py first.")
        return 1
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    # collect all translation lines, keyed by idx
    trans_lines: dict[int, list[str]] = {}
    errors: list[str] = []
    for part in manifest["parts"]:
        pname = part["file"]
        tname = pname.replace("part_", "trans_")
        tpath = os.path.join(parts_dir, tname)
        if not os.path.exists(tpath):
            errors.append(f"Missing translation file: {tname}")
            continue
        with open(tpath, "r", encoding="utf-8") as f:
            tlines = [ln for ln in f if ln.strip()]
        if len(tlines) != part["lines"]:
            errors.append(
                f"{tname}: expected {part['lines']} lines, got {len(tlines)}"
            )
        for ln in tlines:
            fields = parse_trans_line(ln)
            if len(fields) != 5:
                errors.append(f"{tname}: bad field count ({len(fields)}) in line: {ln[:80]!r}")
                continue
            idx = int(fields[0])
            if idx in trans_lines:
                errors.append(f"Duplicate idx {idx} in {tname}")
            trans_lines[idx] = fields

    # continuity check
    expected = manifest["event_count"]
    if len(trans_lines) != expected:
        errors.append(
            f"Idx count mismatch: got {len(trans_lines)}, expected {expected}"
        )
    missing = [i for i in range(1, expected + 1) if i not in trans_lines]
    if missing:
        errors.append(f"Missing idx: {missing[:20]}{'...' if len(missing) > 20 else ''}")

    # per-line validation
    # NOTE: do NOT enforce timeline monotonicity — YouTube ASR subtitles are a
    # rolling window where consecutive lines naturally overlap by 1-2s (multiple
    # speakers / caption windows stack). Overlap is a source property, not an
    # error. The correct check is that every timestamp EXACTLY matches the
    # source (inheritance), which is validated below against subtitle_meta.json
    # when available; otherwise only structural sanity is checked.
    src_events = {}
    meta_path = os.path.join(args.workdir, "subtitle_meta.json")
    if os.path.exists(meta_path):
        try:
            with open(meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
            for i, ev in enumerate(meta.get("events", []), start=1):
                src_events[i] = (ev.get("start"), ev.get("end"))
        except Exception as e:
            log(f"WARN: could not load subtitle_meta.json ({e}); "
                "skipping timestamp-inheritance check")

    for idx in sorted(trans_lines):
        fields = trans_lines[idx]
        start, end = fields[1], fields[2]
        en, zh = fields[3], fields[4]
        if "\t" in en or "\t" in zh:
            errors.append(f"idx {idx}: tab inside text field")
        if "||" in en or "||" in zh:
            errors.append(f"idx {idx}: '||' inside a language field")
        if not en.strip() and not zh.strip():
            errors.append(f"idx {idx}: both languages empty")
        s, e = to_seconds(start), to_seconds(end)
        if s < 0 or e < 0 or e <= s:
            errors.append(f"idx {idx}: bad timestamps {start} -> {end}")
        # inheritance check: translated timestamps must equal the source verbatim
        if idx in src_events:
            src_start, src_end = src_events[idx]
            if (start, end) != (src_start, src_end):
                errors.append(
                    f"idx {idx}: timestamp changed! "
                    f"{start}->{end} vs source {src_start}->{src_end}"
                )

    if errors:
        log("VALIDATION FAILED:")
        for e in errors[:60]:
            log(f"  - {e}")
        if len(errors) > 60:
            log(f"  ... and {len(errors) - 60} more")
        return 1

    # build output
    header = build_standard_header()
    out_lines = [header]
    for idx in sorted(trans_lines):
        _, start, end, en, zh = trans_lines[idx]
        out_lines.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{en}{DELIM}{zh}")

    out_path = os.path.join(args.workdir, resolve_out_name(args))
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines) + "\n")
    log(f"Wrote {len(trans_lines)} lines -> {out_path}")
    log("All checks PASSED.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
